# Generated by Django 4.1.7 on 2023-03-11 13:40

import autoslug.fields
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('short_desc', models.CharField(blank=True, max_length=3000, null=True)),
                ('short_desc1', models.CharField(blank=True, default='add only if you need some extra description for ', max_length=3000, null=True)),
                ('long_description', tinymce.models.HTMLField(blank=True, default='data you will insert here will be on the left side of page make sure to remove it or replace it', null=True)),
                ('long_description_with_points', tinymce.models.HTMLField(blank=True, default='data you will insert here will be on the right side of page make sure to remove it or replace it', null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Self_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('short_desc', models.CharField(blank=True, default='', max_length=500)),
                ('long_desc', models.TextField(blank=True, null=True)),
                ('manager_name', models.CharField(default='', max_length=500, null=True)),
                ('landline1', models.CharField(default='', max_length=100)),
                ('landline2', models.CharField(default='', max_length=100, null=True)),
                ('mobile1', models.CharField(default='', max_length=100, null=True)),
                ('mobile2', models.CharField(default='', max_length=100, null=True)),
                ('personal_mail', models.EmailField(default='', max_length=100, null=True)),
                ('company_mail', models.EmailField(default='', max_length=100)),
                ('location_coordinates', models.CharField(default='', max_length=100, null=True)),
                ('address', models.CharField(default='', max_length=1000, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('long_description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='static/media')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, max_length=700, null=True, populate_from='name', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
