# Generated by Django 4.1.7 on 2023-03-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_management', '0003_team_members_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_members',
            name='profiel_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile_pics_team'),
        ),
    ]
