# Generated by Django 4.1.7 on 2023-03-14 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project_management', '0004_team_members_profiel_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team_members',
            old_name='profiel_picture',
            new_name='profile_picture',
        ),
    ]
