# Generated by Django 4.1.7 on 2023-03-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_management', '0005_rename_profiel_picture_team_members_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
