# Generated by Django 4.1.7 on 2023-03-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_management', '0006_customer_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='self_details',
            name='open_hours',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
