# Generated by Django 4.1.7 on 2023-03-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_management', '0007_self_details_open_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='self_details',
            name='facebook',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='self_details',
            name='instagram',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='self_details',
            name='linkedin',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='self_details',
            name='twitter',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
